### ISSUE TITLE
Reference to unbound identifier: coroutine-stop!

### ISSUE THREAD

**Issue by Zzull** [mighty-gerbils/gerbil-utils#11]
Gerbil-utils doesn't seem to compile with the latest Gerbil:

```
gerbil-utils » ./build.ss
... make deps
*** ERROR IN gx#core-expand-ref% -- Syntax Error
*** ERROR IN "utils/generator.ss"@231.20
--- Syntax Error: Reference to unbound identifier
... form:   (%#ref coroutine-stop!)
... detail: coroutine-stop! at "utils/generator.ss"@231.20
gerbil-utils » gxi
Gerbil v0.15.1 on Gambit v4.9.3
>
```
Isn't it uncommon to get an unbound identifier error on a file that hasn't been touched for a year?

**Comment by fare** [comment]
Upstream Gerbil has changed its API. Gerbil-utils has stopped supporting the old "stable" Gerbil v0.15, and now depends on the API in Gerbil v0.16, currently the development branch.

**Comment by fare** [comment]
Closing the issue. Once a new Gerbil is released, this will be fully resolved.
